# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "virtio_blk"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."crypted".device =
    "/dev/disk/by-uuid/c5c3e4e1-f22d-429f-b3a2-50775c673279";

  fileSystems."/.swapvol" = {
    device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/40D2-3914";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
    # neededForBoot = true;
  };

  #fileSystems."/home/deadbeef" = {
  #  device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
  #  fsType = "btrfs";
  #  options = [ "subvol=home/deadbeef" ];
  #};

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/partition-root" = {
    device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
    fsType = "btrfs";
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/b671ba87-8ef2-41be-af36-eb8904bbd5ee";
    fsType = "btrfs";
    options = [ "subvol=persist" ];
    neededForBoot = true;
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
