keys:
  - &l-portal-u age1a5nn59ea7ut9kw2gu20nv067ptd06zr53vdehlus2mrdgnpny4lsu25nrz
  - &l-portal-r age15z0s6nul3tyn96acegegjsh0rjhalwt2un0vxlltk98qan5aratqfumu56
  - &l-portal-root age1u9tye6zc765aphr3fdvryzwjrw7a3nez4dw7tafveynsvycf7qvskpw6ds
  - &l-portal-u age19xpat8fwf97nkrxcgatny48sz0chrhml5j5ksrqvkyqkpnzp6qjssf0zzs
  - &l-envil-root age1t07vak4hlf47esar8temleglsa2c3lde24q6eu78aaq4a0n0ndqqc0mhp5
  - &l-envil-deadbeef age1d7v0j80lqu7672upwc2fazux9h5e6xt6wmy7wp2svytpzxmc6vysqjp0q8
  - &l-esp-root age1057zl675g0wv59dvzylsu59a35dnv8sc4m8545avl60u5uvdrfpqhjp256
  - &l-esp-deadbeef age1vfresmphe0ahyn9vdtsqzzz72kt2lyd8nya376yk7yxjpc5p298qya76kz
  - &s-sigma-nixos-proxmox-replacement age172vz7pyznaj5sattexdjg43aekx5qv9sjs49axshrlty6ndrdeyskajktk
  - &s-sigma age1lkqlezc852g3svecanwg7ctl2y9ur0qs9pquwjas5dhkhcl9yq5qvr33q2
  - &s-tau age1wkzp7dzxr0fk92zrm2c8eqyhu8hvqzxqlmepsm72yxnhw5x9wseqfn26cp
  - &s-gamma age13v5pme6vzmlclc25zqrmv3gx6qg4lcp5378tp7xrf0vecnlvdcns8semur
  - &s-test-vm-impermanence-root age1zwgk9rqgwgpnzqz0fu5sdkc57sk9gkzk0kx7qw7l3zgacrnvh54srdp94w
  - &s-router-vpn-impermanence-root age1yjk7dkn7swdansateksk0extzns5q02xg8h9w4w97vx9mwnphgxsqywsej
  - &s-router-impermanence-root age1agw6jxjk5r0ttfyevk2m0fa73u73yjjl8nyrq880hslku4mtspxqevpysj
  - &s-lxc-router-root age1nnm22xdfv4ptx0vy3exh24djhmdc4cgc0hjghmk5y4l0hggfcswq8j88j9
  - &s-gameserver age16kxdq47yrc0hzapje3tsplrw6eerdxxzwqzj6emg8yyk6r5dzfcs9xelvd
  - &s-router-edge age1ceu4u9ujawzxctc7kf0f39cwjv7gnv250gnya60muqxa9qxfp5lscvjxj6
  - &s-router-legacy-edge age10n4xywtw8n3xjf6u5zp67hcc5s7htvpetkq0ndvvtyju88uued3s4r686d
  - &s-infra age1866sg8w2ex2ylc2aec5r7xc9uhvgny6v0x8rcmcm6s06jv2gc3jsdjzfmq
  - &s-nebula age1seqn6c56kxch7epv6dr3k43tx5eecj4aktlcg0njqg8ef3ewrvpq9vwsmw
  - &s-test age1n49y8n965sjwt6l8tk2nss5wcsww3qtg0rvqt974sz5npsvmpezs8pllr6
  - &s-router-core age16lrtp9fnvamca3g78pzr4jxcq0nzlj5vs4p5n5jerkxylnwh294syst0yh
  - &s-router-upstream-selector age1xnwyn6yl7mdtnk6jkg5k22pk33x3zfql9r8suqcamfu5w3x2rqmsste7qv
  - &s-router-legacy-core age15vvnx3wd06juu0fc3ywykzdukf7mft2xswl3pmycvtjtvl5unpcq5tdl9l
  - &s-router-access age1e5jk0alk58pksmvqtvfkhwv8prlyd748m8jn7aq5jp88yjfwl9zqx0yn6l
  - &s-router-test age1ry9jff7wmz6aenhhvna4qk280jtnruhhffzwyd6uwa2dljy0p5wqajh9p9
  - &s-router-nixos age1uzapfs5d9x0vt7qpfq9tyqwg8c9yquc745p8qhxulhew30yshcds4n64km
  - &codex-jail age123fj9yey9cvkef5mn6cjqa2e4zrde9wa78ghlkp6vvag7qk65q3qcrat5w
  - &codex-jail-r age1zc8qevlgymsjweav076vk65ae6ef4n9x8fklv6ue45xl4czrqcpqdpepc3
  - &codex-jail-u age198xl6chpupaf6ecyqkcsg2j2mxf0s894csnxxdw6u0m4mjx7qgjqghg498
  - &s-agents-r age1hclj2nd6nakml6jc5l2fmnl7yye9m7at2v7fvfjzktpw9j6f2apqlgnn2l
  - &s-agents-u age15xwz0r777f0lw2zkgw86jdgvqa3ey979udj3rxayta6pjle2k9hshu805h
  - &l-envil-llm-jail age1my0wzset83fpqn8aac7kd4zcdjjmeapxnqy6r9qg36jhe7t8x43qdf7frg
  - &l-envil-llm-jail-root age1lm7ug2rpxh29qu9h38yecqnsu69g6p2qy2v2eesp4uhc43z0x9qs28cwlw
  - &l-envil-llm-jail-user age1z6k6e4ywawn44u83tmwv9304ufaq4ahteszuadechj34jcp9tusqevrm6d
  - &legacy-shared-router age1xm8ftcjlqsns5a4m74593hur7ltuxh2wqcrsl6ja2vqee664dclsq4yrkv
  - &s-router-clab age1dug0ualmuqd5akne2y7zdmwztdwua35c9zle9j3e2540f2me2p3qpp6m6v
  - &hetz-test age1757z4z4t392kxuzfeajuaukh93na90e2p08t06k9ggpw6wa75dsshhqpzw
  - &s-router-prod age18yc5wyyj8mh67r626z0y0n3fpjmh3fq85nd6mk59yedsfs0jea9spfg2zj

creation_rules:
  - path_regex: '^(secrets/)*mail-client\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-root
          - *l-envil-deadbeef
          - *l-esp-root
          - *l-esp-deadbeef
          - *l-portal-root
          - *s-gamma

  - path_regex: '^(secrets/)*s-gamma-runtime\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-root
          - *l-envil-deadbeef
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-gamma

  - path_regex: '^(secrets/)*general-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-portal-u
          - *l-portal-r
          - *l-envil-root
          - *l-envil-deadbeef
          - *l-envil-llm-jail-root
          - *l-envil-llm-jail-user
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-test-vm-impermanence-root
          - *s-router-vpn-impermanence-root
          - *s-router-impermanence-root
          - *legacy-shared-router
          - *s-test

  - path_regex: '^(secrets/)*l-esp-default-deadbeef\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef

  - path_regex: '^(secrets/)*l-esp-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root

  - path_regex: '^(secrets/)*l-envil-default-deadbeef\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-root
          - *l-envil-deadbeef

  - path_regex: '^(secrets/)*l-envil-default.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-root

  - path_regex: '^(secrets/)*s-test-vm-impermanence-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-portal-u
          - *l-portal-r
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-test-vm-impermanence-root
          - *legacy-shared-router

  - path_regex: '^(secrets/)*s-sigma-nixos-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-sigma-nixos-proxmox-replacement

  - path_regex: '^(secrets/)*s-sigma.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-sigma

  - path_regex: '^(secrets/)*s-tau.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-tau

  - path_regex: '^(secrets/)*s-gamma\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-gamma

  - path_regex: '^(secrets/)*s-router-vpn-impermanence-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-portal-u
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-vpn-impermanence-root

  - path_regex: '^(secrets/)*s-router-impermanence-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-portal-u
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-vpn-impermanence-root

  - path_regex: '^(secrets/)*l-portal-.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-deadbeef
          - *l-esp-root
          - *l-portal-root

  - path_regex: '^(secrets/)*s-lxc-router.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-portal-u
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-lxc-router-root
          - *legacy-shared-router
  - path_regex: '^(secrets/)*s-gameserver.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-gameserver
  - path_regex: '^(secrets/)*s-routers.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
          - *s-infra
          - *s-router-core
          - *s-router-access

  - path_regex: '^(secrets/)*s-router-edge.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
          - *s-router-legacy-edge
  - path_regex: '^secrets/vlan2-hostnames-servers\.json\.age$'
    input_type: json
    output_type: json
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
          - *s-router-legacy-edge
          - *s-router-prod

  - path_regex: '^(secrets/)*s-router-legacy-edge.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
          - *s-router-legacy-edge
  - path_regex: '^(secrets/)*s-router-prod.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-prod
  - path_regex: '^(secrets/)*s-router-legacy-core.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-core
          - *s-router-legacy-core
  - path_regex: '^(secrets/)*s-router-prod.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-core
          - *s-router-legacy-core

  - path_regex: '^secrets/isc_export_lan\.csv\.age$'
    input_type: binary
    output_type: binary
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
          - *s-router-legacy-edge

  - path_regex: '^(secrets/)*s-infra.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-infra
  - path_regex: '^(secrets/)*s-nebula.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-nebula
  - path_regex: '^(secrets/)*s-test.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-test
  - path_regex: '^(secrets/)*s-router-core.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-core
  - path_regex: '^(secrets/)*s-router-upstream-selector.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-upstream-selector
  - path_regex: '^(secrets/)*s-router-policy-only.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-edge
  - path_regex: '^(secrets/)*s-router-vpn-egress.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-impermanence-root
          - *legacy-shared-router
  - path_regex: '^(secrets/)*s-router-access.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-access
  - path_regex: '^(secrets/)*s-agents.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-agents-u
          - *s-agents-r
  - path_regex: '^(secrets/)*s-router-(test|nixos).*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-test
          - *s-router-nixos
          - *codex-jail
          - *codex-jail-u
          - *codex-jail-r
  - path_regex: '^(secrets/)*s-router-clab.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-router-test
          - *s-router-nixos
          - *codex-jail
          - *codex-jail-u
          - *codex-jail-r
          - *s-router-clab
  - path_regex: '^(secrets/)*codex-jail.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *codex-jail
          - *codex-jail-u
          - *codex-jail-r
  - path_regex: '^(secrets/)*l-envil-llm-jail.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-llm-jail
          - *l-envil-llm-jail-root
          - *l-envil-llm-jail-user
  - path_regex: '^(secrets/)*s-llm.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-envil-llm-jail
          - *l-envil-llm-jail-root
          - *l-envil-llm-jail-user

  - path_regex: '^(secrets/)*hetz-test.*\.(env|ya?ml)$'
    encrypted_regex: ".*"
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef
          - *l-portal-u
          - *l-portal-r
          - *codex-jail
          - *codex-jail-u
          - *codex-jail-r
          - *hetz-test
