keys:
  - &l-x13s-deadbeef age1xm8ftcjlqsns5a4m74593hur7ltuxh2wqcrsl6ja2vqee664dclsq4yrkv
  - &l-werk-root age1pglvs7ljmfxpx68wmlc2s7s79k6dnm69m0eccdzu8hz56a6hcfrqd8qhgp
  - &l-werk-deadbeef age1vnwm6x6j9grqaejell6df9vr6nzwrdzxwk4wyfjyqva23rxu5c6sswsd6y
  - &l-werk-1-root age1lm7ug2rpxh29qu9h38yecqnsu69g6p2qy2v2eesp4uhc43z0x9qs28cwlw
  - &l-werk-1-deadbeef age1z6k6e4ywawn44u83tmwv9304ufaq4ahteszuadechj34jcp9tusqevrm6d
  - &l-esp-root age1057zl675g0wv59dvzylsu59a35dnv8sc4m8545avl60u5uvdrfpqhjp256
  - &l-esp-deadbeef age1vfresmphe0ahyn9vdtsqzzz72kt2lyd8nya376yk7yxjpc5p298qya76kz
  - &s-test-vm-impermanence-root age1v0jkptx0aulxrapktgptzvn82tt25gyq3qf8hn8e0dyheqwz446qa798t2
  - &s-lxc-router-root age1nnm22xdfv4ptx0vy3exh24djhmdc4cgc0hjghmk5y4l0hggfcswq8j88j9

creation_rules:
  - path_regex: '^(secrets/)*general-.*\.(env|ya?ml)$'
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-x13s-deadbeef
          - *l-werk-root
          - *l-werk-deadbeef
          - *l-werk-1-root
          - *l-werk-1-deadbeef
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-test-vm-impermanence-root

  - path_regex: '^(secrets/)*l-esp-default-deadbeef\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-esp-root
          - *l-esp-deadbeef

  - path_regex: '^(secrets/)*l-esp-.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-esp-root

  - path_regex: '^(secrets/)*l-werk-default-deadbeef\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-werk-root
          - *l-werk-deadbeef
          - *l-werk-1-root
          - *l-werk-1-deadbeef

  - path_regex: '^(secrets/)*l-werk-1-default-deadbeef\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-werk-root
          - *l-werk-1-root
          - *l-werk-deadbeef
          - *l-werk-1-deadbeef

  - path_regex: '^(secrets/)*l-werk-.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-werk-root
          - *l-werk-1-root

          
  - path_regex: '^(secrets/)*s-test-vm-impermanence-.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-x13s-deadbeef
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-test-vm-impermanence-root



  - path_regex: '^(secrets/)*l-x13s-.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-x13s-deadbeef


  - path_regex: '^(secrets/)*s-lxc-router.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    key_groups:
      - age:
          - *l-x13s-deadbeef
          - *l-esp-root
          - *l-esp-deadbeef
          - *s-lxc-router-root
