{ config
, lib
, ...
}:
let
  cfg = config.local.nix.remoteBuilderClient;

  # Aliases so the Nix builder hostnames resolve deterministically and pin the
  # SSH identity, independent of DNS and the calling user's agent.
  sshConfigText = ''
    # Generated by profiles.nixos.nix.remote-builder-client. Do not edit manually.
  '' + lib.concatMapStringsSep "\n"
    (name: ''
      Host ${name}
          HostName ${cfg.builders.${name}.address}
          User nix-ssh
          IdentitiesOnly yes
          IdentityFile /root/.ssh/id_remote-builder
          StrictHostKeyChecking accept-new
    '')
    (builtins.attrNames cfg.builders);

  buildMachines = lib.mapAttrsToList
    (name: m: {
      hostName = name; # alias resolved through /root/.ssh/config
      protocol = "ssh-ng";
      systems = m.systems;
      sshUser = "nix-ssh";
      sshKey = "/root/.ssh/id_remote-builder";
      maxJobs = m.maxJobs;
      speedFactor = m.speedFactor;
      supportedFeatures = m.supportedFeatures;
      mandatoryFeatures = m.mandatoryFeatures;
      publicHostKey = m.publicHostKey;
    })
    cfg.builders;
in
{
  options.local.nix.remoteBuilderClient = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Offload builds to remote ssh-ng builders. Set false to import the profile without enabling offloading.";
    };

    builders = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options = {
            address = lib.mkOption {
              type = lib.types.str;
              description = "Builder address as reachable from this host (e.g. a nebula overlay IP).";
            };
            systems = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              description = "System types this builder can build (include `aarch64-linux` when the builder enables binfmt emulation).";
            };
            maxJobs = lib.mkOption {
              type = lib.types.int;
              default = 8;
            };
            speedFactor = lib.mkOption {
              type = lib.types.int;
              default = 2;
            };
            supportedFeatures = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
            };
            mandatoryFeatures = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
            };
            publicHostKey = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Base64 of the builder sshd host key (see `base64 -w0 /etc/ssh/ssh_host_ed25519_key.pub`).";
            };
          };
        }
      );
      default = {
        # The shared remote-builder fleet. Both hosts are x86_64 and emulate
        # aarch64 via binfmt, so they serve every client system in the herd.
        s-sigma-builder = {
          address = "100.64.0.16";
          systems = [ "x86_64-linux" "aarch64-linux" ];
          supportedFeatures = [ "nixos-test" "benchmark" "big-parallel" "kvm" ];
        };
        s-tau-builder = {
          address = "100.64.0.17";
          systems = [ "x86_64-linux" "aarch64-linux" ];
          supportedFeatures = [ "nixos-test" "benchmark" "big-parallel" "kvm" ];
        };
      };
      description = "Remote builders to offload to, keyed by an SSH alias.";
    };
  };

  config = lib.mkIf cfg.enable {
    nix = {
      inherit buildMachines;

      distributedBuilds = true;

      settings = {
        builders-use-substitutes = true;
        fallback = true;
        connect-timeout = 5;
      };
    };

    # Materialize the root SSH client config on the real filesystem (not the Nix
    # store). The shared builder identity (/root/.ssh/id_remote-builder) is
    # generated once on the client:
    #   sudo ssh-keygen -t ed25519 -N "" -C "root@$(hostname)-remote-builder" -f /root/.ssh/id_remote-builder
    # and its .pub must be added to every builder's
    # local.nix.remoteBuilderServer.clients.<host>.key. Persist /root/.ssh via the
    # host's impermanence setup (already the case on these hosts).
    system.activationScripts.nixRemoteBuilderClientSshConfig = {
      deps = [ ];
      text = ''
        mkdir -p /root/.ssh
        chmod 700 /root/.ssh
        cat > /root/.ssh/config <<'EOF'
        ${sshConfigText}
        EOF
        chmod 600 /root/.ssh/config
      '';
    };
  };
}
