{ config
, lib
, ...
}:
let
  cfg = config.local.nix.remoteBuilderClient;

  # Builders that are not explicitly excluded for this host. A host that is
  # itself part of the shared fleet must exclude its own builder alias so it
  # does not try to offload builds to itself over SSH.
  enabledBuilders = lib.filterAttrs
    (name: _: !(lib.elem name cfg.excludeBuilders))
    cfg.builders;

  # Aliases so the Nix builder hostnames resolve deterministically and pin the
  # SSH identity, independent of DNS and the calling user's agent.
  sshConfigText = ''
    # Generated by profiles.nixos.nix.remote-builder-client. Do not edit manually.
  '' + lib.concatMapStringsSep "\n"
    (name: ''
      Host ${name}
          HostName ${cfg.builders.${name}.address}
          User nix-ssh
          IdentitiesOnly yes
          IdentityFile /root/.ssh/id_remote-builder
          StrictHostKeyChecking accept-new
    '')
    (builtins.attrNames enabledBuilders);

  buildMachines = lib.mapAttrsToList
    (name: m: {
      hostName = name; # alias resolved through /root/.ssh/config
      protocol = "ssh-ng";
      systems = m.systems;
      sshUser = "nix-ssh";
      sshKey = "/root/.ssh/id_remote-builder";
      maxJobs = m.maxJobs;
      speedFactor = m.speedFactor;
      supportedFeatures = m.supportedFeatures;
      mandatoryFeatures = m.mandatoryFeatures;
      publicHostKey = m.publicHostKey;
    })
    enabledBuilders;
in
{
  options.local.nix.remoteBuilderClient = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Offload builds to remote ssh-ng builders. Set false to import the profile without enabling offloading.";
    };

    excludeBuilders = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Builder aliases to omit from this host's build machines (e.g. a host's own alias when it is also part of the fleet).";
    };

    builders = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options = {
            address = lib.mkOption {
              type = lib.types.str;
              description = "Builder address as reachable from this host (e.g. a nebula overlay IP).";
            };
            systems = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              description = "System types this builder can build (include `aarch64-linux` when the builder enables binfmt emulation).";
            };
            maxJobs = lib.mkOption {
              type = lib.types.int;
              default = 8;
            };
            speedFactor = lib.mkOption {
              type = lib.types.int;
              default = 2;
            };
            supportedFeatures = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
            };
            mandatoryFeatures = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
            };
            publicHostKey = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Base64 of the builder sshd host key (see `base64 -w0 /etc/ssh/ssh_host_ed25519_key.pub`).";
            };
          };
        }
      );
      default = {
        # The shared remote-builder fleet. s-sigma and s-tau are x86_64 and
        # emulate aarch64 via binfmt, so they serve every client system in the
        # herd. l-envil only serves x86_64: it is a laptop with fewer cores and
        # keeps its aarch64 emulation off.
        s-sigma-builder = {
          address = "100.64.0.16";
          systems = [ "x86_64-linux" "aarch64-linux" ];
          supportedFeatures = [ "nixos-test" "benchmark" "big-parallel" "kvm" ];
        };
        s-tau-builder = {
          address = "100.64.0.17";
          systems = [ "x86_64-linux" "aarch64-linux" ];
          supportedFeatures = [ "nixos-test" "benchmark" "big-parallel" "kvm" ];
        };
        l-envil-builder = {
          address = "100.64.0.13";
          systems = [ "x86_64-linux" ];
          # i9-13900H: 14 cores / 20 threads, also used interactively and for
          # local LLM workloads. Cap concurrent jobs well below the server
          # builders' 8 so offloads do not saturate the laptop.
          maxJobs = 4;
        };
        l-esp-builder = {
          address = "100.64.0.10";
          systems = [ "x86_64-linux" ];
          # i7-12850HX: 16 cores / 24 threads, interactive laptop. Same cap as
          # l-envil.
          maxJobs = 4;
        };
        l-portal-builder = {
          address = "100.64.0.14";
          # The only native aarch64 builder (ThinkPad X13s). It does not emulate,
          # so it serves aarch64 only. Weakest host: 8 cores / 14 GiB, capped to
          # 2 jobs; speedFactor 1 so clients prefer the emulating servers.
          systems = [ "aarch64-linux" ];
          maxJobs = 2;
          speedFactor = 1;
        };
      };
      description = "Remote builders to offload to, keyed by an SSH alias.";
    };
  };

  config = lib.mkIf cfg.enable {
    nix = {
      inherit buildMachines;

      distributedBuilds = true;

      settings = {
        builders-use-substitutes = true;
        fallback = true;
        connect-timeout = 5;
      };
    };

    # Materialize the root SSH client config on the real filesystem (not the Nix
    # store). The shared builder identity (/root/.ssh/id_remote-builder) is
    # generated once on the client:
    #   sudo ssh-keygen -t ed25519 -N "" -C "root@$(hostname)-remote-builder" -f /root/.ssh/id_remote-builder
    # and its .pub must be added to every builder's
    # local.nix.remoteBuilderServer.clients.<host>.key. Persist /root/.ssh via the
    # host's impermanence setup (already the case on these hosts).
    system.activationScripts.nixRemoteBuilderClientSshConfig = {
      deps = [ ];
      text = ''
        mkdir -p /root/.ssh
        chmod 700 /root/.ssh
        cat > /root/.ssh/config <<'EOF'
        ${sshConfigText}
        EOF
        chmod 600 /root/.ssh/config
      '';
    };
  };
}
