# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3604a002-d8d9-4fb5-ad03-e72234d04225";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/5e780f27-96e9-4881-8f23-256199cd766f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/149B-25CB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3604a002-d8d9-4fb5-ad03-e72234d04225";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/3604a002-d8d9-4fb5-ad03-e72234d04225";
      fsType = "btrfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/3604a002-d8d9-4fb5-ad03-e72234d04225";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/vmstore" =
    { device = "/dev/disk/by-uuid/3604a002-d8d9-4fb5-ad03-e72234d04225";
      fsType = "btrfs";
      options = [ "subvol=vmstore" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens20.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens21.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
