# # Do not modify this file!  It was generated by ‘nixos-generate-config’
# # and may be overwritten by future invocations.  Please make changes
# # to /etc/nixos/configuration.nix instead.
# { config, lib, pkgs, modulesPath, ... }:

# {
#   imports = [ ];

#   boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "megaraid_sas" "nvme" "usbhid" "usb_storage" ];
#   boot.initrd.kernelModules = [ ];
#   boot.kernelModules = [ "kvm-intel" ];
#   boot.extraModulePackages = [ ];

#   fileSystems."/" =
#     { device = "rpool/data/subvol-100-disk-0";
#       fsType = "zfs";
#     };

#   swapDevices = [ ];

#   # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
#   # (the default) this is the recommended approach. When using systemd-networkd it's
#   # still possible to use this option, but it's recommended to use it in conjunction
#   # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
#   networking.useDHCP = lib.mkDefault true;
#   # networking.interfaces.bonding_masters.useDHCP = lib.mkDefault true;
#   # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
# # nixpkgs.hostPlatform = "24.11";
#   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
# }

{
  config,
  modulesPath,
  pkgs,
  lib,
  ...
}:
{
  imports = [ (modulesPath + "/virtualisation/proxmox-lxc.nix") ];
  nix.settings = {
    sandbox = false;
  };
  proxmoxLXC = {
    manageNetwork = true;
    privileged = false;
  };
  #security.pam.services.sshd.allowNullPassword = true;
  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PermitRootLogin = "yes";
      PasswordAuthentication = true;
      #PermitEmptyPasswords = "yes";
    };
  };
  # system.stateVersion = "24.11";
}
