#!/usr/bin/env bash
set -euo pipefail

root=
realised=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --add-root)
      shift
      root="$1"
      ;;
    --realise)
      shift
      realised="$1"
      ;;
  esac
  shift
done

test -n "$root"
test -n "$realised"
ln -sfn "$realised" "$root"
printf '%s\n' "$realised"
