# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  #boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/004c1bab-e066-4b32-81b4-b42232fb9b34";
  #    fsType = "ext4";
  #  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c9569225-27ed-4c49-a7d9-090e72c58577";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/679D-75A1";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };
  #fileSystems."/boot" = {
  #  device = "/dev/disk/by-uuid/679D-75A1";
  #  fsType = "vfat";
  #  options = [ "fmask=0077" "dmask=0077" ];
  #};

  #boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/F56F4756-60F0-46C8-A28E-8C82692DD515";
  #  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/f56f4756-60f0-46c8-a28e-8c82692dd515";
  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/be6d5b2f-d108-4535-9646-249bd6ac8630";

  #  fileSystems."/boot" =
  #    { device = "/dev/disk/by-uuid/4EBC-A879";
  #      fsType = "vfat";
  #      options = [ "fmask=0022" "dmask=0022" ];
  #    };

  #swapDevices = [ ];
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 45 * 1024;
    }
  ];
  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u4u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.lxcbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
