{ pkgs
, config
, libs
, ...
}:

{

  # Enable OpenGL
  hardware.graphics = {
    enable = true;
  };

  # Load nvidia driver for Xorg and Wayland
  #services.xserver.videoDrivers = ["nvidia"];
  services.supergfxd.enable = true;

  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.powerManagement.enable = false;
  hardware.nvidia.powerManagement.finegrained = false;
  hardware.nvidia.open = true;
  hardware.nvidia.nvidiaSettings = true;
  hardware.nvidia-container-toolkit.enable = true;
  #hardware.nvidia.prime = {
  #  offload.enable = true;
  #  intelBusId = "PCI:0:2:0";   # Intel iGPU Bus ID
  #  nvidiaBusId = "PCI:1:0:0";  # NVIDIA dGPU Bus ID
  #};
  # Generated by the script, checking if it hates leading 0's
  hardware.nvidia.prime = {
    offload.enable = true;
    offload.enableOffloadCmd = true;
    intelBusId = "PCI:00:02:0"; # Intel GPU Bus ID
    nvidiaBusId = "PCI:01:00:0"; # NVIDIA GPU Bus ID
  };

  # nixpkgs.config.cudaSupport = true;

  services.xserver.videoDrivers = [ "nvidia" ];
  #hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta; # this somehow works??!
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable; # testing if this works still...

  # Regular Docker
  virtualisation.docker.daemon.settings.features.cdi = true;
  # Rootless
  virtualisation.docker.rootless.daemon.settings.features.cdi = true;

  # cuda runtime
  #environment.systemPackages = [
  #  (pkgs.ollama.override {
  #    acceleration = "cuda";
  #  })
  #];
  #services.ollama.acceleration = "cuda";

}
