{
  config,
  lib,
  pkgs,
  sopsSecrets,
  ...
}:

{

  # xsession.windowManager.i3 = {
  #   enable = true;
  #   configFile = "${config.home.homeDirectory}/.config/i3/config";
  # };

  home.file.".config/i3/config.test".text = ''
    # This file has been auto-generated by i3-config-wizard(1).
    # It will not be overwritten, so edit it as you like.
    #
    for_window [class="burp-StartBurp" title="licensed to ${builtins.readFile config.sops.secrets.burpLicenseCompanyname.path}"] move container to workspace 8
  ''
}