# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/f4586b06-9326-44dd-b70b-68559b8b342c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8B39-0006";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
      options = [ "subvol=games" ];
    };

  fileSystems."/home/deadbeef" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
      options = [ "subvol=home/deadbeef" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/39247b05-a959-4580-8229-4c66726e3a1e";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
