{ config
, lib
, pkgs
, ...
}:
let
  thunar = pkgs.thunar or pkgs.xfce.thunar;
in

{
  home.file.".config/i3/config" = {
    text = ''
      # this file is generated by home-manager, check the repository from systemctl status nixos-upgrade.service to update this.

      # i3 config file (v4)
      #
      # Please see https://i3wm.org/docs/userguide.html for a complete reference!

      set $mod Mod4

      # Font for window titles. Will also be used by the bar unless a different font
      # is used in the bar {} block below.
      #font pango:monospace 12
      #font pango:monospace 18
      #font pango:monospace 12
      #font pango:monospace 14
      font pango:monospace 10

      # This font is widely installed, provides lots of unicode glyphs, right-to-left
      # text rendering and scalability on retina/hidpi displays (thanks to pango).
      #font pango:DejaVu Sans Mono 8

      # Start XDG autostart .desktop files using dex. See also
      # https://wiki.archlinux.org/index.php/XDG_Autostart
      exec --no-startup-id ${pkgs.dex}/bin/dex --autostart --environment i3

      # The combination of xss-lock, nm-applet and pactl is a popular choice, so
      # they are included here as an example. Modify as you see fit.

      # xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
      # screen before suspend. Use loginctl lock-session to lock your screen.
      #exec --no-startup-id ${pkgs.xss-lock}/bin/xss-lock --transfer-sleep-lock -- i3lock --nofork

      # NetworkManager is the most popular way to manage wireless networks on Linux,
      # and nm-applet is a desktop environment-independent system tray GUI for it.
      exec --no-startup-id ${pkgs.networkmanagerapplet}/bin/nm-applet

      # Use pactl to adjust volume in PulseAudio.
      set $refresh_i3status killall -SIGUSR1 i3status
      bindsym XF86AudioRaiseVolume exec --no-startup-id ${pkgs.pulseaudio}/bin/pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
      bindsym XF86AudioLowerVolume exec --no-startup-id ${pkgs.pulseaudio}/bin/pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
      bindsym XF86AudioMute exec --no-startup-id ${pkgs.pulseaudio}/bin/pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
      bindsym XF86AudioMicMute exec --no-startup-id ${pkgs.pulseaudio}/bin/pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
      # Media player controls
      bindsym XF86AudioPlay exec ${pkgs.playerctl}/bin/playerctl play-pause
      bindsym XF86AudioPause exec ${pkgs.playerctl}/bin/playerctl play-pause
      bindsym XF86AudioStop exec ${pkgs.playerctl}/bin/playerctl stop
      bindsym XF86AudioNext exec ${pkgs.playerctl}/bin/playerctl next
      bindsym XF86AudioPrev exec ${pkgs.playerctl}/bin/playerctl previous

      # brightness

      # Screen brightness controls:
      bindsym XF86MonBrightnessUp exec --no-startup-id "${pkgs.brightnessctl}/bin/brightnessctl set +10%"
      bindsym XF86MonBrightnessDown exec --no-startup-id "${pkgs.brightnessctl}/bin/brightnessctl set 10%-"

      # Use Mouse+$mod to drag floating windows to their wanted position
      floating_modifier $mod

      # start a terminal
      bindsym $mod+Return exec ${pkgs.alacritty}/bin/alacritty

      # kill focused window
      # kill is from coreutils, i can not do dynamic paths here:
      bindsym $mod+q kill

      #exec_always --no-startup-id export GTK2_RC_FILES=/usr/share/themes/Raleigh/gtk-2.0/gtkrc
      #exec --no-startup-id "source $HOME/.xprofile"
      #exec --no-startup-id "zsh -l -c 'export GTK2_RC_FILES=/usr/share/themes/Raleigh/gtk-2.0/gtkrc'"


      # start dmenu (a program launcher)
      #bindsym $mod+d exec --no-startup-id "dmenu_run"
      #bindsym $mod+d exec --no-startup-id "${pkgs.rofi}/bin/rofi -modi drun,run -show drun"
      bindsym $mod+d exec --no-startup-id "${pkgs.rofi}/bin/rofi -modi drun,run -show drun"
      bindsym $mod+Shift+d exec --no-startup-id "${pkgs.rofi}/bin/rofi -show window"

      # A more modern dmenu replacement is rofi:
      # bindcode $mod+40 exec "${pkgs.rofi}/bin/rofi -modi drun,run -show drun"
      # There also is i3-dmenu-desktop which only displays applications shipping a
      # .desktop file. It is a wrapper around dmenu, so you need that installed.
      # bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop

      # change focus
      bindsym $mod+j focus left
      bindsym $mod+k focus down
      bindsym $mod+l focus up
      bindsym $mod+semicolon focus right

      # alternatively, you can use the cursor keys:
      bindsym $mod+Left focus left
      bindsym $mod+Down focus down
      bindsym $mod+Up focus up
      bindsym $mod+Right focus right

      # move focused window
      bindsym $mod+Shift+j move left
      bindsym $mod+Shift+k move down
      bindsym $mod+Shift+l move up
      bindsym $mod+Shift+semicolon move right

      # alternatively, you can use the cursor keys:
      bindsym $mod+Shift+Left move left
      bindsym $mod+Shift+Down move down
      bindsym $mod+Shift+Up move up
      bindsym $mod+Shift+Right move right

      # split in horizontal orientation
      bindsym $mod+h split h

      # split in vertical orientation
      bindsym $mod+v split v

      # enter fullscreen mode for the focused container
      bindsym $mod+f fullscreen toggle

      # change container layout (stacked, tabbed, toggle split)
      bindsym $mod+s layout stacking
      bindsym $mod+w layout tabbed
      bindsym $mod+e layout toggle split

      # toggle tiling / floating
      bindsym $mod+Shift+space floating toggle

      # change focus between tiling / floating windows
      bindsym $mod+space focus mode_toggle

      # focus the parent container
      bindsym $mod+a focus parent

      # focus the child container
      #bindsym $mod+d focus child

      # Define names for default workspaces for which we configure key bindings later on.
      # We use variables to avoid repeating the names in multiple places.
      set $ws1 "1"
      set $ws2 "2"
      set $ws3 "3"
      set $ws4 "4"
      set $ws5 "5"
      set $ws6 "6"
      set $ws7 "7"
      set $ws8 "8"
      set $ws9 "9"
      set $ws10 "10"

      # switch to workspace
      bindsym $mod+1 workspace number $ws1
      bindsym $mod+2 workspace number $ws2
      bindsym $mod+3 workspace number $ws3
      bindsym $mod+4 workspace number $ws4
      bindsym $mod+5 workspace number $ws5
      bindsym $mod+6 workspace number $ws6
      bindsym $mod+7 workspace number $ws7
      bindsym $mod+8 workspace number $ws8
      bindsym $mod+9 workspace number $ws9
      bindsym $mod+0 workspace number $ws10

      # move focused container to workspace
      bindsym $mod+Shift+1 move container to workspace number $ws1
      bindsym $mod+Shift+2 move container to workspace number $ws2
      bindsym $mod+Shift+3 move container to workspace number $ws3
      bindsym $mod+Shift+4 move container to workspace number $ws4
      bindsym $mod+Shift+5 move container to workspace number $ws5
      bindsym $mod+Shift+6 move container to workspace number $ws6
      bindsym $mod+Shift+7 move container to workspace number $ws7
      bindsym $mod+Shift+8 move container to workspace number $ws8
      bindsym $mod+Shift+9 move container to workspace number $ws9
      bindsym $mod+Shift+0 move container to workspace number $ws10

      # reload the configuration file
      bindsym $mod+Shift+c reload
      # restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
      bindsym $mod+Shift+r restart
      # lock the screen
      bindsym $mod+Shift+x exec ${pkgs.betterlockscreen}/bin/betterlockscreen -l dimblur
      # exit i3 (logs you out of your X session)
      bindsym $mod+Shift+e exec "${pkgs.i3}/bin/i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' '${pkgs.i3}/bin/i3-msg exit ; ${pkgs.procps}/bin/pkill X ; ${pkgs.procps}/bin/pkill xfce4-session'"
      # resize window (you can also use the mouse for that)
      mode "resize" {
              # These bindings trigger as soon as you enter the resize mode

              # Pressing left will shrink the window’s width.
              # Pressing right will grow the window’s width.
              # Pressing up will shrink the window’s height.
              # Pressing down will grow the window’s height.
              bindsym j resize shrink width 10 px or 10 ppt
              bindsym k resize grow height 10 px or 10 ppt
              bindsym l resize shrink height 10 px or 10 ppt
              bindsym semicolon resize grow width 10 px or 10 ppt
              
      	# or with shift to be more precice
              bindsym Shift+j resize shrink width 1 px or 1 ppt
              bindsym Shift+k  resize grow height 1 px or 1 ppt
              bindsym Shift+l resize shrink height 1 px or 1 ppt
              bindsym Shift+semicolon resize grow width 1 px or 1 ppt

              # same bindings, but for the arrow keys
              bindsym Left resize shrink width 10 px or 10 ppt
              bindsym Down resize grow height 10 px or 10 ppt
              bindsym Up resize shrink height 10 px or 10 ppt
              bindsym Right resize grow width 10 px or 10 ppt

              # back to normal: Enter or Escape or $mod+r
              bindsym Return mode "default"
              bindsym Escape mode "default"
              bindsym $mod+r mode "default"
      }

      bindsym $mod+t mode "resize"


      # Start i3bar to display a workspace bar (plus the system information i3status
      # finds out, if available)
      #bar {
      #        #status_command i3status
      #        #font pango:DejaVu Sans Mono, FontAwesome 10
      #        font pango:BlexMono Nerd Font Mono Regular, BlexMono Nerd Font Mono Bold, 10
      #
      #        status_command i3status-rs
      ##colors {
      ##        background #000000
      ##        statusline #111111
      ##    }

              
      #}

      bar {
          status_command ${pkgs.i3status-rust}/bin/i3status-rs ~/.config/i3status-rust/config.toml
          #i3bar_command i3bar --transparency
          #font pango:IBM Plex Mono, Material Icons 12
          #position bottom
          #tray_output primary
          #mode hide
          #hidden_state hide
          modifier $mod
          workspace_min_width 40
          colors {
              separator #282a36
              background #282a3670
              statusline #f8f8f2
              focused_workspace #50fa7b70 #50fa7b #282a36
              active_workspace #8be9fd70 #8be9fd #282a36
              inactive_workspace #282a3670 #282a3670 #f8f8f2
              urgent_workspace #2f343a70 #ff555570 #282a36
          }
          #padding 0
      }

      gaps inner 15
      gaps outer 10
      smart_gaps on


      # deadbeefs config
      focus_follows_mouse no
      gaps inner 2
      gaps outer 2

      mode "exit: [l]ogout, [r]eboot, [s]hutdown" {
        bindsym l exec ${pkgs.i3}/bin/i3-msg exit
        bindsym r exec systemctl reboot
        bindsym s exec systemctl shutdown
        bindsym Escape mode "default"
        bindsym Return mode "default"
      }
      bindsym $mod+m mode "exit: [l]ogout, [r]eboot, [s]hutdown"

      bindsym $mod+i exec ${thunar}/bin/thunar
      bindsym $mod+F4 exec ${pkgs.legcord}/bin/legcord

      bindsym $mod+Escape exec ${pkgs.i3lock}/bin/i3lock -n -i /home/deadbeef/Pictures/background/captureWebpageEachMonitorDifferentPage/img/combined_screenshot.png
      bindsym $mod+c exec google-chrome-stable
      bindsym $mod+F3 exec spotify
      exec --no-startup-id ${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1
      exec --no-startup-id ${pkgs.networkmanagerapplet}/bin/nm-applet

      # --no-sandbox
      bindsym $mod+F2 exec teams  

      # flameshot crashes
      bindsym Print exec "${pkgs.flameshot}/bin/flameshot gui"
      # Replace Flameshot with Ksnip for Print key
      # bindsym Print exec "sway-screenshot -m region"
      bindsym $mod+Print+Shift exec "sway-screenshot -m window -- mirage"

      # Add Alt + Print to open Ksnip
      bindsym $mod+Print exec "${pkgs.ksnip}/bin/ksnip"

      # move workspace to the left.
      bindsym $mod+comma move workspace to output left
      bindsym $mod+period move workspace to output right


      bindsym $mod+bracketright exec ${pkgs.pamixer}/bin/pamixer --increase 10
      bindsym $mod+bracketleft exec ${pkgs.pamixer}/bin/pamixer --decrease 10

      for_window [class="google-chrome" class="Google-chrome"] move window to workspace 2
      for_window [class="Chromium" title=".*"] move container to workspace 2
      for_window [class="Spotify"] move to workspace 4
      for_window [class="Slack"] move window to workspace 5
      for_window [class="discord"] move to workspace 5
      for_window [class="legcord"] move to workspace 5
      for_window [class="Navigator" class="firefox"] move window to workspace 8
      for_window [class="Firefox"] move window to workspace 8
      for_window [class="firefox"] move window to workspace 8
      for_window [class="burp-StartBurp" title="^Burp Suite Professional$"] move container to workspace 10
      for_window [class="burp-StartBurp" title="Automatic project backup"] move container to workspace 10

      bindsym $mod+b exec --no-startup-id ${pkgs.xdotool}/bin/xdotool click 8
      bindsym $mod+shift+b exec --no-startup-id ${pkgs.xdotool}/bin/xdotool click 9
      bindsym Mod1+b exec --no-startup-id ${pkgs.xdotool}/bin/xdotool click 8
      bindsym Mod1+shift+b exec --no-startup-id ${pkgs.xdotool}/bin/xdotool click 9



      exec --no-startup-id export XDG_SESSION_TYPE=x11
      exec --no-startup-id xsetroot -solid "#333333" #gray
      exec --no-startup-id xsetroot -solid "#000000"
      exec --no-startup-id ${pkgs.picom}/bin/picom
      exec --no-startup-id ${pkgs.autorandr}/bin/autorandr
      exec --no-startup-id ${pkgs.dunst}/bin/dunst
      exec --no-startup-id ${pkgs.legcord}/bin/legcord

      # disable numlock
      exec --no-startup-id ${pkgs.numlockx}/bin/numlockx off
      exec_always --no-startup-id ${pkgs.autotiling}/bin/autotiling
    '';
  };
}
