creation_rules:
  - path_regex: '^general-.*\.(env|ya?ml)$'
    encrypted_regex: '.*'
    age:
      - age1xm8ftcjlqsns5a4m74593hur7ltuxh2wqcrsl6ja2vqee664dclsq4yrkv
      - age1vfresmphe0ahyn9vdtsqzzz72kt2lyd8nya376yk7yxjpc5p298qya76kz

  - path_regex: l-esp-.*\.env$
    input_type: env
    encrypted_regex: '.*'
    age: age1vfresmphe0ahyn9vdtsqzzz72kt2lyd8nya376yk7yxjpc5p298qya76kz
  - path_regex: '^l-x13s-.*\.(env|ya?ml)$'
    input_type: env
    encrypted_regex: '.*'
    # generate a public key with either the sops/age/keys.txt
    # nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt"
    # and generate a public key like so:
    # age-keygen -y ~/.config/sops/age/keys.txt
    # same as:
    # nix-shell -p ssh-to-age --run "ssh-to-age < ~/.ssh/id_ed25519.pub"
    age: age1xm8ftcjlqsns5a4m74593hur7ltuxh2wqcrsl6ja2vqee664dclsq4yrkv
# .sops.yaml